# Generated by Django 5.2.14 on 2026-06-23 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_subadmin', models.BooleanField(default=False, verbose_name='Sub-admin')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Owner')),
            ],
        ),
    ]
