# Generated by Django 5.2.14 on 2026-06-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE UNIQUE INDEX IF NOT EXISTS auth_user_email_uniq ON auth_user (email);',
            reverse_sql='DROP INDEX IF EXISTS auth_user_email_uniq;'
        )
    ]
