# Generated by Django 5.2.14 on 2026-06-15 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_alter_department_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_admin', 'Chờ Sub-admin xử lý'), ('pending_owner', 'Chờ Owner xử lý'), ('rejected_by_admin', 'Sub-admin từ chối')], default='pending_admin', max_length=30, verbose_name='Trạng thái')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do yêu cầu')),
                ('review_note', models.TextField(blank=True, verbose_name='Ghi chú xử lý (Sub-admin)')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Thời hạn xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('requester', models.ForeignKey(limit_choices_to={'groups__name': 'requester'}, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'sub-admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Sub-admin xử lý')),
            ],
            options={
                'verbose_name': 'Yêu cầu cấp quyền',
                'verbose_name_plural': 'Yêu cầu cấp quyền',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='access_requests.accessrequest', verbose_name='Yêu cầu')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='applications.application', verbose_name='Ứng dụng')),
            ],
            options={
                'verbose_name': 'Mục yêu cầu',
                'verbose_name_plural': 'Mục yêu cầu',
                'unique_together': {('access_request', 'application')},
            },
        ),
    ]
