# Generated by Django 5.2.14 on 2026-06-17 07:00

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.CharField(default=utils.PrefixedIdGenerator('req'), editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_admin', 'Chờ Sub-admin xử lý'), ('pending_owner', 'Chờ Owner xử lý'), ('rejected_by_admin', 'Sub-admin từ chối'), ('completed', 'Đã hoàn thành')], default='pending_admin', max_length=30, verbose_name='Trạng thái')),
                ('reason', models.TextField(blank=True, verbose_name='Lý do yêu cầu')),
                ('review_note', models.TextField(blank=True, verbose_name='Ghi chú xử lý (Sub-admin)')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Thời hạn xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian xử lý')),
                ('requester', models.ForeignKey(limit_choices_to={'groups__name': 'requester'}, on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'sub-admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Sub-admin xử lý')),
            ],
            options={
                'verbose_name': 'Yêu cầu cấp quyền',
                'verbose_name_plural': 'Yêu cầu cấp quyền',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerBatch',
            fields=[
                ('id', models.CharField(default=utils.PrefixedIdGenerator('batch'), editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Chờ gửi'), ('sent', 'Đã gửi cho Owner')], default='waiting', max_length=20, verbose_name='Trạng thái')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian gửi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_batches', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Batch gửi Owner',
                'verbose_name_plural': 'Batch gửi Owner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.CharField(default=utils.PrefixedIdGenerator('item'), editable=False, max_length=40, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting_batch', 'Chờ gửi batch'), ('pending_owner', 'Chờ Owner xử lý'), ('approved', 'Đã duyệt'), ('rejected_by_owner', 'Owner từ chối'), ('rejected_by_admin', 'Sub-admin thu hồi')], default='waiting_batch', max_length=20, verbose_name='Trạng thái')),
                ('owner_note', models.TextField(blank=True, verbose_name='Ghi chú của Owner')),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='access_requests.accessrequest', verbose_name='Yêu cầu')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='applications.application', verbose_name='Ứng dụng')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='access_requests.ownerbatch', verbose_name='Batch')),
            ],
            options={
                'verbose_name': 'Mục yêu cầu',
                'verbose_name_plural': 'Mục yêu cầu',
                'unique_together': {('access_request', 'application')},
            },
        ),
    ]
