# Generated by Django 5.2.14 on 2026-06-16 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='owner_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú của Owner'),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('waiting_batch', 'Chờ gửi batch'), ('pending_owner', 'Chờ Owner xử lý'), ('approved', 'Đã duyệt'), ('rejected', 'Đã từ chối')], default='waiting_batch', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending_admin', 'Chờ Sub-admin xử lý'), ('pending_owner', 'Chờ Owner xử lý'), ('rejected_by_admin', 'Sub-admin từ chối'), ('completed', 'Đã hoàn thành')], default='pending_admin', max_length=30, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='OwnerBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Chờ gửi'), ('sent', 'Đã gửi cho Owner')], default='waiting', max_length=20, verbose_name='Trạng thái')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian gửi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='access_requests.accessrequest', verbose_name='Yêu cầu')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_batches', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Batch gửi Owner',
                'verbose_name_plural': 'Batch gửi Owner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='requestitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='access_requests.ownerbatch', verbose_name='Batch'),
        ),
    ]
