# Generated by Django 5.2.14 on 2026-06-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='dispute_reason',
            field=models.TextField(blank=True, verbose_name='Lý do khiếu nại'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian khiếu nại'),
        ),
    ]
