# Generated by Django 5.2.14 on 2026-06-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0002_add_dispute_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending_admin', 'Chờ Sub-admin xử lý'), ('pending_owner', 'Chờ Owner xử lý'), ('rejected_by_admin', 'Sub-admin từ chối'), ('completed', 'Đã hoàn thành'), ('canceled', 'Đã hủy')], default='pending_admin', max_length=30, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('waiting_batch', 'Chờ gửi batch'), ('pending_owner', 'Chờ Owner xử lý'), ('approved', 'Đã duyệt'), ('rejected_by_owner', 'Owner từ chối'), ('rejected_by_admin', 'Sub-admin thu hồi'), ('canceled', 'Đã hủy')], default='waiting_batch', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
