# Generated by Django 5.2.14 on 2026-06-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0002_requestitem_owner_note_requestitem_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerbatch',
            name='access_request',
        ),
    ]
