# Generated by Django 5.2.14 on 2026-06-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0003_remove_ownerbatch_access_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('waiting_batch', 'Chờ gửi batch'), ('pending_owner', 'Chờ Owner xử lý'), ('approved', 'Đã duyệt'), ('rejected_by_owner', 'Owner từ chối')], default='waiting_batch', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
