# Generated by Django 5.2.14 on 2026-06-23 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0003_alter_accessrequest_status_alter_requestitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__is_subadmin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Sub-admin xử lý'),
        ),
        migrations.AlterField(
            model_name='ownerbatch',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__is_owner': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_batches', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
