# Generated by Django 5.2.14 on 2026-06-12 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên phòng ban')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã phòng ban')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Phòng ban',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên domain')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã domain')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='applications.department', verbose_name='Phòng ban')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domain',
                'ordering': ['department', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên ứng dụng')),
                ('code', models.CharField(max_length=100, verbose_name='Mã ứng dụng')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Ứng dụng',
                'verbose_name_plural': 'Ứng dụng',
                'ordering': ['domain', 'name'],
                'unique_together': {('name', 'domain')},
            },
        ),
    ]
