# Generated by Django 5.2.14 on 2026-06-23 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_domains', to=settings.AUTH_USER_MODEL, verbose_name='Sub-admin quản lý'),
        ),
        migrations.AlterField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__is_owner': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
