# Generated by Django 5.2.15 on 2026-06-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'PNL', 'verbose_name_plural': 'PNL'},
        ),
    ]
