# Generated by Django 5.2.14 on 2026-06-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_department_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('code', 'domain'), ('name', 'domain')},
        ),
    ]
